"""Add History model for audit trail

Revision ID: 40a256798f94
Revises: 690c72633831
Create Date: 2025-08-26 17:10:34.927087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a256798f94'
down_revision: Union[str, Sequence[str], None] = '690c72633831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('portfolio_id', sa.String(length=8), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('time', sa.String(length=6), nullable=False),
    sa.Column('seq_no', sa.String(length=4), nullable=False),
    sa.Column('record_type', sa.String(length=2), nullable=True),
    sa.Column('action_code', sa.String(length=1), nullable=True),
    sa.Column('before_image', sa.Text(), nullable=True),
    sa.Column('after_image', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.String(length=4), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=True),
    sa.Column('process_user', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.port_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'date', 'time', 'seq_no')
    )
    op.create_index('idx_history_action_code', 'history', ['action_code'], unique=False)
    op.create_index('idx_history_date', 'history', ['date'], unique=False)
    op.create_index('idx_history_portfolio_id', 'history', ['portfolio_id'], unique=False)
    op.create_index('idx_history_record_type', 'history', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_record_type', table_name='history')
    op.drop_index('idx_history_portfolio_id', table_name='history')
    op.drop_index('idx_history_date', table_name='history')
    op.drop_index('idx_history_action_code', table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
