"""Initial schema from COBOL structures

Revision ID: 65eeed226e0d
Revises: 
Create Date: 2025-08-26 15:34:23.428068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65eeed226e0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('port_id', sa.String(length=8), nullable=False),
    sa.Column('account_no', sa.String(length=10), nullable=False),
    sa.Column('client_name', sa.String(length=30), nullable=True),
    sa.Column('client_type', sa.String(length=1), nullable=True),
    sa.Column('create_date', sa.String(length=8), nullable=True),
    sa.Column('last_maint', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('last_user', sa.String(length=8), nullable=True),
    sa.Column('last_trans', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('port_id', 'account_no')
    )
    op.create_index('idx_portfolio_client_type', 'portfolios', ['client_type'], unique=False)
    op.create_index('idx_portfolio_status', 'portfolios', ['status'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', sa.String(length=8), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('investment_id', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('last_maint_date', sa.String(length=26), nullable=True),
    sa.Column('last_maint_user', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.port_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'date', 'investment_id')
    )
    op.create_index('idx_position_date', 'positions', ['date'], unique=False)
    op.create_index('idx_position_investment_id', 'positions', ['investment_id'], unique=False)
    op.create_index('idx_position_portfolio_id', 'positions', ['portfolio_id'], unique=False)
    op.create_index('idx_position_status', 'positions', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('time', sa.String(length=6), nullable=False),
    sa.Column('portfolio_id', sa.String(length=8), nullable=False),
    sa.Column('sequence_no', sa.String(length=6), nullable=False),
    sa.Column('investment_id', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('process_date', sa.String(length=26), nullable=True),
    sa.Column('process_user', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.port_id'], ),
    sa.PrimaryKeyConstraint('date', 'time', 'portfolio_id', 'sequence_no')
    )
    op.create_index('idx_transaction_date', 'transactions', ['date'], unique=False)
    op.create_index('idx_transaction_investment_id', 'transactions', ['investment_id'], unique=False)
    op.create_index('idx_transaction_portfolio_id', 'transactions', ['portfolio_id'], unique=False)
    op.create_index('idx_transaction_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_transaction_type', 'transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_type', table_name='transactions')
    op.drop_index('idx_transaction_status', table_name='transactions')
    op.drop_index('idx_transaction_portfolio_id', table_name='transactions')
    op.drop_index('idx_transaction_investment_id', table_name='transactions')
    op.drop_index('idx_transaction_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_position_status', table_name='positions')
    op.drop_index('idx_position_portfolio_id', table_name='positions')
    op.drop_index('idx_position_investment_id', table_name='positions')
    op.drop_index('idx_position_date', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_portfolio_status', table_name='portfolios')
    op.drop_index('idx_portfolio_client_type', table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
